version: "3"

services:
  api:
    build: api
    command: "flask run -h 0.0.0.0 -p 5000"
    environment:
      - FLASK_DEBUG=false
      - FLASK_APP=app/app.py
    ports:
      - "${API_PORT-:5000}:5000"

  client:
    build: client
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - "${CLIENT_PORT-:3000}:3000"
    links:
      - api
    depends_on:
      - api
